#!/bin/bash
#
# .xprofile: set basic X11 environment
#

# Background image
BACKGROUND=""

# Session applications
PROGRAMS=""

# Make sure to load the profile
source $HOME/.profile

# Start xscreensaver
xscreensaver -no-splash &

# Custom
if [ -e "$HOME/.custom/xprofile" ]; then
  source $HOME/.custom/xprofile
fi

# Set background
if [ ! -z "$BACKGROUND" ]; then
  Esetroot -scale $HOME/.config/themes/backgrounds/$BACKGROUND
else
  xsetroot -solid black
fi

# Additional applications depending on the machine type
if laptop-detect; then
  PROGRAMS="$PROGRAMS wicd-client"
else
  PROGRAMS="$PROGRAMS"
fi

# Start session applications
for program in $PROGRAMS; do
  $program &
done

# See https://bugzilla.redhat.com/show_bug.cgi?id=783568
#     https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/932177
unset GNOME_KEYRING_PID
unset GNOME_KEYRING_CONTROL
